#!/usr/bin/env bash
# script that trasnfers a file from client to server

if [[ $# -lt 4 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

filepath=$1
server=$2
username=$3
ssh_keys=$4

echo "StrictHostKeyChecking no" >> ~/.ssh/config

scp -i "$ssh_keys" "$filepath" "$username"@"$server":~/
