#!/usr/bin/env bash
# install nginx

sudo apt-get install -y nginx

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

sudo service nginx restart

response=$(curl -s http://localhost)
if [[ $response == *"Hello World!"* ]]; then
    echo "$response"
fi
