#!/usr/bin/env bash
# Install nginx, set up to listen to port 80 and change default page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# configure redirection
new_str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUl\
wu4 permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default
sudo service nginx restart
