#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
scp ubuntu@3.83.18.255:/etc/nginx/nginx.conf /etc/nginx
echo "add_header X-Served-By \$hostname;" >> /etc/nginx/nginx.conf
sudo service nginx restart
