#!/usr/bin/env bash
# debugging skills

# check if nginx configuration is set to listen to port 80
if ! grep -q "listen 80;" /etc/nginx/sites-enabled/default; then
    echo "nginx not setup to listen to port 80"
    sudo sed -i 's/listen 8080;/listen 80;/g'
    sudo service nginx restart
fi
