#!/usr/bin/env bash
# Displays Best school 10 times Hi after the 9th

i=0
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((i++))
done
