#!/usr/bin/env bash
# run nginx as nginx

sudo service nginx stop
sudo sed -i 's/listen.*/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default
sudo sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
sudo service nginx start
