#!/usr/bin/env bash
# run nginx as nginx

# sudo service nginx stop
# sudo sed -i 's/listen.*/listen 0.0.0.0:8080;/' /etc/nginx/sites-available/default
# sudo sed -i 's/user.*/user nginx;/' /etc/nginx/nginx.conf
# sudo service nginx start

pkill apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/d\
efault
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
service nginx reload
service nginx restart
