#!/usr/bin/env bash
# script that uses ssh to connect to your server using
# private key with the user ubuntu

keyfile=~/.ssh/school
username=ubuntu
host=54.236.26.141

ssh -t -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" "$username"@"$host"
